### ISSUE TITLE
dataset preprocess

### ISSUE THREAD

**Issue by noahcao** [benjiebob/3D-Multibodies#1]
Hi Benjamin,

is there a guideline about how to preprocess the dataset?

**Comment by noahcao** [comment]
I assumed you followed [the convention by SPIN](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md). But as you didn't mention this in README, I would like to confirm it here to avoid potential misalignment.

**Comment by benjiebob** [comment]
That's right, this repo follows the SPIN convention for data preparation.
