### ISSUE TITLE
2D Weak Supervision for Human3.6M

### ISSUE THREAD

**Issue by GloryyrolG** [benjiebob/3D-Multibodies#2]
Hi Benjamin,

Thanks for your spotlight work and public code!

May I ask, if there are no 2D keypoints (GT or OpenPose) in `h36m_valid_protocol*.npz`?

Regards,

**Comment by benjiebob** [comment]
h36m_valid_protocol*.npz is used for evaluation only and I don't think we ever did a 2D evaluation (as 3D is much more reliable where possible). This might explain why they are missing. 

If memory serves, I think we got these npz files from the [SPIN](https://github.com/nkolot/SPIN) repository. They have [instructions](https://github.com/nkolot/SPIN/blob/master/datasets/preprocess/README.md#generate-dataset-files) for how to generate the 2D data.

**Comment by GloryyrolG** [comment]
I see. Based on your responses to [the previous issue](https://github.com/benjiebob/3D-Multibodies/issues/3), the repo currently only verifies the evaluation. Thanks for the clarification.
