### ISSUE TITLE
Theta for H36M

### ISSUE THREAD

**Issue by GloryyrolG** [benjiebob/3D-Multibodies#4]
Hi Benjie,

For training on (A)H36M, it seems $\Theta$ annotations are required. Did you release this data?

Thanks & Regards,

**Comment by benjiebob** [comment]
Hi @GloryyrolG - unfortunately due to license limitations we cannot release the SMPL parameters for H36M. However, as suggested in the [SPIN library](https://github.com/nkolot/SPIN#run-training-code) it should be possible to train using alternative datasets where these parameters are available.

**Comment by GloryyrolG** [comment]
Hi Benjie,

May I know what resources of SMPL parameters you used to train the model? Is that from [SMPLify-X](https://github.com/JiangWenPL/multiperson/tree/master/misc/smplify-x), [NeuralAnnot](https://github.com/mks0601/NeuralAnnot_RELEASE), or [Mosh](http://mosh.is.tue.mpg.de/), _etc._?

Thanks & Regards, Happy New Year
